spring.application.name=orders-batch

spring.datasource.url=jdbc:postgresql://localhost:5432/orders
spring.datasource.username=orders
spring.datasource.password=orders

spring.batch.jdbc.initialize-schema=always

orders.input-dir=input
orders.staging-dir=staging

spring.sql.init.mode=always